
package org.json4s

import models._

import org.specs2.mutable.Specification
import text.Document


class JSONParserSpec extends Specification {

    val classMaps = JSONParser.storeClassFields(jsonSchema)


 "a ClassFieldStore" should {
    "contain a key corresponding to each record in the JSON schema" in {

    val mapContainsClasses = classMaps.keys.toSet.subsetOf(Set("TUPLE_0", "TUPLE_1", "TUPLE_2", "TUPLE_3", "TUPLE_4"))  
 
    mapContainsClasses === true
    }
  }


  lazy val jsonSchema = """
{
   "type":"record",
   "name":"TUPLE_0",
   "fields":[
      {
         "name":"message_id",
         "type":[
            "null",
            "string"
         ],
         "doc":"autogenerated from Pig Field Schema"
      },
      {
         "name":"date",
         "type":[
            "null",
            "string"
         ],
         "doc":"autogenerated from Pig Field Schema"
      },
      {
         "name":"from",
         "type":[
            "null",
            {
               "type":"record",
               "name":"TUPLE_1",
               "fields":[
                  {
                     "name":"address",
                     "type":[
                        "null",
                        "string"
                     ],
                     "doc":"autogenerated from Pig Field Schema"
                  },
                  {
                     "name":"name",
                     "type":[
                        "null",
                        "string"
                     ],
                     "doc":"autogenerated from Pig Field Schema"
                  }
               ]
            }
         ],
         "doc":"autogenerated from Pig Field Schema"
      },
      {
         "name":"subject",
         "type":[
            "null",
            "string"
         ],
         "doc":"autogenerated from Pig Field Schema"
      },
      {
         "name":"body",
         "type":[
            "null",
            "string"
         ],
         "doc":"autogenerated from Pig Field Schema"
      },
      {
         "name":"tos",
         "type":[
            "null",
            {
               "type":"array",
               "items":[
                  "null",
                  {
                     "type":"record",
                     "name":"TUPLE_2",
                     "fields":[
                        {
                           "name":"address",
                           "type":[
                              "null",
                              "string"
                           ],
                           "doc":"autogenerated from Pig Field Schema"
                        },
                        {
                           "name":"name",
                           "type":[
                              "null",
                              "string"
                           ],
                           "doc":"autogenerated from Pig Field Schema"
                        }
                     ]
                  }
               ]
            }
         ],
         "doc":"autogenerated from Pig Field Schema"
      },
      {
         "name":"ccs",
         "type":[
            "null",
            {
               "type":"array",
               "items":[
                  "null",
                  {
                     "type":"record",
                     "name":"TUPLE_3",
                     "fields":[
                        {
                           "name":"address",
                           "type":[
                              "null",
                              "string"
                           ],
                           "doc":"autogenerated from Pig Field Schema"
                        },
                        {
                           "name":"name",
                           "type":[
                              "null",
                              "string"
                           ],
                           "doc":"autogenerated from Pig Field Schema"
                        }
                     ]
                  }
               ]
            }
         ],
         "doc":"autogenerated from Pig Field Schema"
      },
      {
         "name":"bccs",
         "type":[
            "null",
            {
               "type":"array",
               "items":[
                  "null",
                  {
                     "type":"record",
                     "name":"TUPLE_4",
                     "fields":[
                        {
                           "name":"address",
                           "type":[
                              "null",
                              "string"
                           ],
                           "doc":"autogenerated from Pig Field Schema"
                        },
                        {
                           "name":"name",
                           "type":[
                              "null",
                              "string"
                           ],
                           "doc":"autogenerated from Pig Field Schema"
                        }
                     ]
                  }
               ]
            }
         ],
         "doc":"autogenerated from Pig Field Schema"
      }
   ]
}
  """
}
